### ISSUE TITLE
Does not parse currency symbol after amount

### ISSUE THREAD

**Issue by imargonis** [RubyMoney/monetize#108]
Monetize.parse seems to only look in front of the value and ignores anything after. It is common for EUR to be written after the value.
```
> Monetize.assume_from_symbol = true
 => true
> price = "13,23 €"
=> "13,23 €"
> Monetize.parse(price)
 => #<Money fractional:1323 currency:USD>
> price = "€ 13,56"
 => "€ 13,56"
> Monetize.parse(price)
 => #<Money fractional:1356 currency:EUR>
```

**Comment by antstorm** [comment]
@imargonis that's a really good point, I'll have a look at solving it. You are also welcome to submit a PR if you have time

**Comment by BKDruby** [comment]
@antstorm How could I make PR? 

I can't push my branch to repo.

**Comment by antstorm** [comment]
@BKDruby sweet! You should be able to open a pull request on the `monetize` repo, comparing your fork's `master` with base `master`

**Comment by mensfeld** [comment]
Any update on this one?

**Comment by antstorm** [comment]
@mensfeld doesn't look like it. @BKDruby any news?

We might need to rethink how `monetize` does parsing, because there's a number of other issues with the current solution.

**Comment by antstorm** [comment]
Should have been fixed by https://github.com/RubyMoney/monetize/pull/131, closing. Please feel free to re-open if there are still issues
