### ISSUE TITLE
[v1.9.1] Monetize.parse does not take into account rounding mode

### ISSUE THREAD

**Issue by FunkyloverOne** [RubyMoney/monetize#125]
Here's an example with Banker's Rounding mode:
```ruby
Money.from_amount(1.545, :usd)
# => #<Money fractional:154 currency:USD>

Monetize.parse!('1.545 USD')
# => #<Money fractional:155 currency:USD>
```

Perhaps it's already fixed on master.

**Comment by antstorm** [comment]
Yes, here's the commit — https://github.com/RubyMoney/monetize/commit/e5700edbd353c3f9668db377b1c75d16de4216db

I'll release v1.9.2
