### ISSUE TITLE
CDN isn't recognized as Canadian Currency

### ISSUE THREAD

**Issue by devonpmack** [RubyMoney/monetize#128]
Was trying to parse prices from amazon in Canada and they use CDN instead of CAD as the identifier.

To reproduce:
`"CDN$ 5.00".to_money`
Result:
`Monetize::ParseError Exception: Unknown currency 'cdn'`

**Comment by antstorm** [comment]
What is CDN? It's not listed as part of the ISO 4217. You can alway define your own currency with `Money::Currency.register`

**Comment by devonpmack** [comment]
Thanks!
