### ISSUE TITLE
wrong parsing when currency symbol after amount

### ISSUE THREAD

**Issue by BKDruby** [RubyMoney/monetize#129]
Monetize.parse('2,50€')
=> Money fractional:250 currency:USD

**Comment by fvarnals** [comment]
Hi @BKDruby - you need to enable the ability to assume the currency from a passed symbol, by using:

```Monetize.assume_from_symbol = true```

before you run 

```Monetize.parse('2,50€')```

Otherwise, currency symbols will be ignored, and USD used as the default currency:

**Comment by antstorm** [comment]
@BKDruby good spot, I've opened a PR to fix it ^
