### ISSUE TITLE
undefined method `default_currency' for Money:Class

### ISSUE THREAD

**Issue by fvarnals** [RubyMoney/monetize#130]
Hi there,

When I use the Gem in a REPL, it works fine, but when I try to run from RSpec, I keep getting the error:

```undefined method `default_currency' for Money:Class```

This happens when calling Monetize.parse 

I'm using monetize version 1.9.2

**Comment by antstorm** [comment]
@fvarnals hey, sorry for a long response. Are you still having this issue? How do you load the `monetize` gem? `Money.default_currency` should come from the `money` gem, which this gem depends on. If you're using bundler it should have resolved this dependency

**Comment by antarr** [comment]
I'm having this issue when trying to use with `act_as_money`

```
require 'monetize'

module CollectiveIdea #:nodoc:
  module Acts
    module Money #:nodoc:
      def self.included(base) #:nodoc:
        base.extend ClassMethods
      end

      module ClassMethods
        def money(name, options = {})
          options = {:cents => :cents, :currency => :currency}.merge(options)
          mapping = [[options[:cents].to_s, 'cents']]
          mapping << [options[:currency].to_s, 'currency'] if options[:currency]

          composed_of name, :class_name => 'Money', :allow_nil => true, :mapping => mapping do |m|
            # m.to_money
            Monetize.parse(m)
          end
        end
      end
    end
  end
end
```

**Comment by antstorm** [comment]
@antarr is there anything specific about your setup? Can you please post a stack trace?
