### ISSUE TITLE
Parsing Euro with iso code and assume_from_symbol returns ZAR

### ISSUE THREAD

**Issue by ricobl** [RubyMoney/monetize#132]
After the `1.9.3` release, parsing any iso code ending with an `R` returns currency as ZAR when `assume_from_symbol` is on as demonstrated here:

```ruby
irb(main):001:0> require 'monetize'
=> true
irb(main):002:0> 'EUR -13.00'.to_money
=> #<Money fractional:-1300 currency:EUR>
irb(main):003:0> Monetize.assume_from_symbol = true
=> true
irb(main):004:0> 'EUR -13.00'.to_money
=> #<Money fractional:-1300 currency:ZAR>
irb(main):005:0>
```

https://github.com/RubyMoney/monetize/commit/8bfb079ef3664baee2d0fe62702d57e727b1c96f is the only code change in that release, so it has probably something to do with that regex. The last char on the iso code seems to be matching the symbol.

**Comment by antstorm** [comment]
@ricobl thanks for noticing! The regexp used to detect a symbol that is at the beginning of a string or just after a sign. We probably need to restrict it to fix the issue you found… I'll have a look shortly

**Comment by ricobl** [comment]
No worries @antstorm. Thanks for chasing this.

**Comment by antstorm** [comment]
@ricobl opened a PR to fix the issue ^, hope I'm not missing any weird use-cases

**Comment by ricobl** [comment]
> @ricobl opened a PR to fix the issue ^, hope I'm not missing any weird use-cases

Looks good, I made a review there. Thanks @antstorm.

**Comment by antstorm** [comment]
The new version (1.9.4) should be out now. Thanks again for bringing this up 👍

**Comment by ricobl** [comment]
Awesome, thanks for the quick release.
