### ISSUE TITLE
Problem parsing VND string with thousand delimiter

### ISSUE THREAD

**Issue by andychongyz** [RubyMoney/monetize#139]
Hi guys, I found this problem when parsing VND string. Is this a bug, or is meant to work like this?
`Monetize.parse("568,000 VND")` should be parsed into 56800000 cents but instead, parsed into 568 cents.

Current temporary solution:
```ruby
# Monkeypatch the parse method as it passing string with VND wrongly
Monetize.module_eval do
  def self.parse(input, currency = Money.default_currency, options = {})
    input.delete!(",") if input.to_s.include?("VND")
    parse! input, currency, options
  rescue Monetize::Error
    nil
  end
end
```

**Comment by antstorm** [comment]
It looks like the expected thousands separator for VND is `.`, which confuses the parser. I'm working on rewriting the parser which should allow to use localized values.

To solve this in the current version you can try re-registering the currency and swapping `thousands_separator` and `decimal_mark` places. Hope this helps
