### ISSUE TITLE
CodeClimate maintainability badge is not working

### ISSUE THREAD

**Issue by tagliala** [RubyMoney/monetize#169]
This issue _may_ have been caused from the renaming of `master` to `main`.

In that case, an action should be performed on Code Climate by someone who has access:

> To move forward, you need to switch the default branch of those repos in Code Climate to master/main, and trigger a successful build. You should then be able to access your repository as expected.

Note: this cannot be fixed with a PR

**Comment by tagliala** [comment]
Hi @allolex, sorry for the mention and thanks for the reviews.

This cannot be fixed with a PR, if you have access to CodeClimate the fix should be trivial

**Comment by allolex** [comment]
@semmons99 Can you look at this? 🙏

**Comment by semmons99** [comment]
fixed
