### ISSUE TITLE
Documented behavior for `.parse`/`.parse!` changed in 1.13.0

### ISSUE THREAD

**Issue by shirts** [RubyMoney/monetize#172]
The [Usage](https://github.com/RubyMoney/monetize?tab=readme-ov-file#usage) describes the default behavior of `Monetize.parse` and `Monetize.parse!` returning `nil` and raising an error respectively if an unknown currency is passed in. It looks like [this PR](https://github.com/RubyMoney/monetize/pull/167/files), specifically [this line](https://github.com/RubyMoney/monetize/pull/167/files#diff-7e5d8c34fac08dd3e8d68769c89584a9d5744ac6219c2f43c6c263a4d0fb2b55R79) changed that behavior:

```ruby
[2]> Monetize.parse('OMG 100')
=> #<Money fractional:10000 currency:USD>

[3]> Monetize.parse!('OMG 100')
=> #<Money fractional:10000 currency:USD>
```

Was this intentional? If so, could the documentation be updated to reflect these changes? 

Thanks!

cc @kahshing96 @semmons99

**Comment by semmons99** [comment]
Since it works this way at the moment, I think we update the docs. Mind submitting a PR with the update. If someone wants to argue for a major release that breaks this usage, I am open to consider it.

Cheers.
🤘SE
