### ISSUE TITLE
Invalid amount parsed as 0 when default currency used

### ISSUE THREAD

**Issue by mmustala** [RubyMoney/monetize#174]
Hey,

Just found out that 1.12 version used to raise an exception when trying to `Monetize.parse('FOO USD', 'EUR')` but now it returns `#<Money fractional:0 currency:EUR>`. Also `parse!` seems to do the same.

Is there a way to get the old functionality back with some config? Or needs a PR?

**Comment by shirts** [comment]
FYI I raised this issue earlier today in https://github.com/RubyMoney/monetize/issues/172

**Comment by semmons99** [comment]
believe we cleared this in #173

**Comment by mmustala** [comment]
@semmons99 #173 only updated documentation, so is this change intentional? Or I'm just missing the code changes?

**Comment by semmons99** [comment]
intentional. a PR with a failing test demonstration this is preferred to an open issue for how we try and run this project. we do this to help bring community collaboration and accountability to the project—hard learned lessons from 15 years on this project.
