### ISSUE TITLE
Silent fallback to default currency is error-prone and inconsistent with Money.from_amount

### ISSUE THREAD

**Issue by mpkhr** [RubyMoney/monetize#176]
Since upgrade to v1.13.0 the the following behavior is inconsistent
```
random_currency = Faker::Currency.code       # e.g. MAD
Monetize.parse("#{random_currency} 499.99")  # #<Money fractional:49999 currency:EUR>
Money.from_amount(499.99, random_currency)   # #<Money fractional:49999 currency:MAD>
```

Likely related to https://github.com/RubyMoney/monetize/issues/172 but in my opinion worse than the case described there.

**Comment by semmons99** [comment]
please submit a PR for consideration.

**Comment by mpkhr** [comment]
Thanks for getting back on this topic! I'm not familiar with the internals of Monetize and don't have the extra time to creating a PR. However, since it was fine before, would you what the issue might be? Or even better, a fix or workaround?

**Comment by semmons99** [comment]
I don't. Perhaps someone who 👍 the issue will have the passion to dive in.
