### ISSUE TITLE
[DEPRECATION] `Money.infinite_precision` is deprecated - use `Money.default_infinite_precision` instead

### ISSUE THREAD

**Issue by mwolman** [RubyMoney/monetize#177]
I have a project that uses `Ruby 2.7` and `Rails 7.1` and I'm getting this deprecation everywhere:
```
[DEPRECATION] `Money.infinite_precision` is deprecated - use `Money.default_infinite_precision` instead
``` 
Can you upgrade `money` to [6.14.0](https://github.com/RubyMoney/money/blob/main/CHANGELOG.md#6140) where they fix this issue? Thank you 🤗

**Comment by semmons99** [comment]
please submit a PR for consideration
