### ISSUE TITLE
Parsing Lists and Ranges

### ISSUE THREAD

**Issue by bensheldon** [RubyMoney/monetize#35]
Would you be open to accepting a PR for parsing lists of values or ranges? 

The API I'm thinking of would be something like this:

```ruby
Monetize.parse("$100 - $200", multiple: true)
```

which would always return an instance of something like `Monetize::Multiple` which would be an enumerable (having first, last, each, etc) containing Money objects. It would additionally have methods of 

```ruby
Monetize::Multiple#range?
Monetize::Multiple#list?
```

for reporting whether the parsed string was a range or list.

I wrote something similar just using raw string parsing (without the Money library) but I'd like to align it with Money (I made the noob mistake of parsing currency as floats): https://github.com/bensheldon/fuzzy_money/blob/master/spec/lib/fuzzy_money/price_spec.rb

I'm happy to submit it as a PR against your library or create another gem. Let me know what you'd prefer. Thanks!

**Comment by semmons99** [comment]
I'd love a PR like this. I'd name the method `Monetize.parse_range` to be more explicit. Also, how would it iterate, unit or subunit? Would it just be configurable?

**Comment by bensheldon** [comment]
My preference would be to have a single method of `Monetize.parse_multiple` rather than separate `parse_range` and `parse_list` methods. My use case is transforming random values collected from the internet, so I don't really know ahead of time whether I'm parsing a single value ($10), a range ($10 - $15) or multiple values (£8/10€/$12). 

In my simple/naive implementation, I preserve the order of the original string. So in pseudocode it would look something like:

```ruby
Monetize.parse_multiple('$10') #=> [ Monetize.parse('$10') ]
Monetize.parse_multiple('$10 - $15') #=> [ Monetize.parse('$10'), Monetize.parse('$15') ], range? == true
Monetize.parse_multiple('8£/10€/$12') #=> [ Monetize.parse('£8'), Monetize.parse('10€'),  Monetize.parse('$15') ]
```

If it's implemented using `Enumerable` anyone could write their own [custom comparator](http://www.ruby-doc.org/core-2.2.0/Enumerable.html#method-i-sort).

**Comment by bensheldon** [comment]
Oh, I realized now you were asking about range in regards to being something like `($10...$15).each { |value| }`. I haven't really thought of that at all. I was only thinking of purely parsing a string with multiple values into a collection of Money objects.

**Comment by semmons99** [comment]
Is you idea of parsing `$100 - $200` when doing an each would just return `$100` and `$200`, not everything in that range?

**Comment by bensheldon** [comment]
> Is you idea of parsing $100 - $200 when doing an each would just return $100 and $200, not everything in that range?

Yes. My need is the ability parse a string with multiple values into a collection of Money objects, than creating a new kind of Money object with Range-like semantics.

So in thinking about it more, maybe it would be clearer to call the object `Monetize::Collection` and `Monetize.parse_collection('8£/10€/$12')` so it's clear that it operates more like an Array than a Range.

**Comment by semmons99** [comment]
That's a much stronger abstraction.

**Comment by takiy33** [comment]
I close this issue because https://github.com/RubyMoney/monetize/pull/36 is merged.
