### ISSUE TITLE
Readme.md usage confusingly ordered

### ISSUE THREAD

**Issue by urbanautomaton** [RubyMoney/monetize#37]
Hi,

The Usage section of the readme shows as its first example:

```ruby
Monetize.parse("$100") == Money.new(100_00, "USD")
Monetize.parse("€100") == Money.new(100_00, "EUR")
Monetize.parse("£100") == Money.new(100_00, "GBP")
```

However these examples only work as shown if `Monetize.assume_from_symbol = true` has previously been set. Without it, they all equal `Money.new(100_00, "USD")`, with the currency only being picked up if it's specified as an ISO code:

```
$ irb
irb(main):001:0> require 'monetize'
=> true
irb(main):002:0> Monetize.parse("£100")
=> #<Money fractional:10000 currency:USD>
irb(main):003:0> Monetize.parse("GBP 100")
=> #<Money fractional:10000 currency:GBP>
```

This is a bit confusing, since the `assume_from_symbol` option defaults to nil, isn't mentioned until after these examples, and then only in the context of `String#to_money`. To me it reads as if the first examples are intended to work as shown without this option set.

All the best,
Simon

**Comment by semmons99** [comment]
Mind updating the README then?

**Comment by urbanautomaton** [comment]
Not at all, just wanted to be sure this was actually the intended behaviour. PR to follow.
