### ISSUE TITLE
JPY and USD are parsed in a different way

### ISSUE THREAD

**Issue by mmustala** [RubyMoney/monetize#41]
Is this expected behavior?

```
jruby-1.7.17 :045 > Monetize.parse(10.33, 'USD')
 => #<Money fractional:1033 currency:USD> 
jruby-1.7.17 :046 > Monetize.parse(10.33, 'JPY')
 => #<Money fractional:10 currency:JPY> 
```

Parsing the same amount in USD and JPY gives a different result. I would have expected also JPY amount to be 1033 in cents.

Using
money 6.5.1
monetize 1.1.0

**Comment by mmustala** [comment]
It might be because of these currency configurations in the money gem. According to the Wikipedia http://en.wikipedia.org/wiki/Japanese_yen JPY has  a subunit "sen". Should these configurations be updated? It would change the behavior for the users who might have been used to the current way how the parsing works. 
```
jruby-1.7.17 :009 > Monetize.parse('1033.00', 'JPY').currency
 => #<Money::Currency id: jpy, priority: 6, symbol_first: true, thousands_separator: ,, html_entity: &#x00A5;, decimal_mark: ., name: Japanese Yen, symbol: ¥, subunit_to_unit: 1, exponent: 0.0, iso_code: JPY, iso_numeric: 392, subunit: , smallest_denomination: 1> 
jruby-1.7.17 :011 > Monetize.parse('1033.00', 'USD').currency
 => #<Money::Currency id: usd, priority: 1, symbol_first: true, thousands_separator: ,, html_entity: $, decimal_mark: ., name: United States Dollar, symbol: $, subunit_to_unit: 100, exponent: 2.0, iso_code: USD, iso_numeric: 840, subunit: Cent, smallest_denomination: 1> 
```

**Comment by semmons99** [comment]
JPY doesn't have a subunit, so without infinite precision, you lose the .33

**Comment by mmustala** [comment]
Ok.
I also noticed that my use of the resulting Money object was not good in this kind of situation where the currency has no subunit. I used `Monetize(amount.to_s.upcase, currency).cents / 100.0` to get the amount as float. Now I changed this to simply use `to_f` for the returned Money object.

**Comment by semmons99** [comment]
If you use the `:YEN` backwards compatible currency, you can have Sen even though it's not used anymore. The other option is to enable infinite precision. Be wary of using `to_f` The whole point of the money gem is to avoid all the pitfalls of floats.
