### ISSUE TITLE
NameError: uninitialized constant Monetize::Collection::Forwardable

### ISSUE THREAD

**Issue by davidsklar** [RubyMoney/monetize#44]
After `gem install monetize`, a `require 'monetize'` gives me:

````
NameError: uninitialized constant Monetize::Collection::Forwardable
	from /usr/local/lib/ruby/gems/2.2.0/gems/monetize-1.2.0/lib/collection.rb:7:in `<class:Collection>'
        .....
````

This looks to be a similar situation as, e.g. https://github.com/resque/resque/issues/1128

If I do `require 'forwardable'` before I require monetize, then it works fine.

So perhaps change (as is suggested in the resque comment) "extend Forwardable" to "extend ::Forwardable" ?

If it matters, this is with monetize 1.2.0 and ruby -v says "ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]"

**Comment by semmons99** [comment]
could you submit a patch?

**Comment by duderonomy** [comment]
When using the default gem specifier in my Gemfile, the lock file looked like this: 
```
GEM
  remote: https://rubygems.org/
  specs:
    i18n (0.7.0)
    monetize (1.3.0)
      money (~> 6.5.0)
    money (6.5.1)
      i18n (>= 0.6.4, <= 0.7.0)
```

I saw this error:

```
$ ruby ./object_model/monetize_example.rb 
/Users/dx/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/monetize-1.3.0/lib/collection.rb:7:in `<class:Collection>': uninitialized constant Monetize::Collection::Forwardable (NameError)
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/monetize-1.3.0/lib/collection.rb:6:in `<module:Monetize>'
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/monetize-1.3.0/lib/collection.rb:5:in `<top (required)>'
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/monetize-1.3.0/lib/monetize.rb:6:in `<top (required)>'
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from ./object_model/monetize_example.rb:9:in `<main>'
```

Then, after removing:
```
gem uninstall monetize
gem uninstall money
```

After inserting the github specifier for monetize:
`gem "monetize", :github => "RubyMoney/monetize"`

And after running bundle install, my Gemfile.lock looked like this:
```
GIT
  remote: git://github.com/RubyMoney/monetize.git
  revision: 535ae0d6be98092f794ec298f84fc3840896fc6b
  specs:
    monetize (1.3.0)
      money (~> 6.5.0)

GEM
  remote: https://rubygems.org/
  specs:
    i18n (0.7.0)
    money (6.5.1)
      i18n (>= 0.6.4, <= 0.7.0)
```

When trying to use it:
```
 $ ruby ./object_model/monetize_example.rb 
/Users/dx/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- monetize (LoadError)
	from /Users/dx/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./object_model/monetize_example.rb:9:in `<main>'

```

**Comment by semmons99** [comment]
Pretty sure we fixed this in master. Just need to release. I'll do it later tonight. 



- shane

**Comment by duderonomy** [comment]
Hey thanks very much for your prompt response!

Perhaps I can get some validation from you about my usage of tools such as
github and bundler.

When I used the github option in bundler, didn't I pull the change you
speak of, from master branch?
I was trying to report that this change did yielded another error on ruby
2.2.2.
I should try 2.1 or 1.9 :)

Please let me know if I am misguided in my observations. My Gemfile.lock
indicated this commit was the latest one that I got:
remote: git://github.com/RubyMoney/monetize.git
  revision: 535ae0d6be98092f794ec298f84fc3840896fc6b

many thanks.
-k


​

**Comment by semmons99** [comment]
You're right. Let me know if you solve it. I'll hold off on a release. 



- shane

**Comment by duderonomy** [comment]
Issue #44 is confusing.
```
$ gem install forwardable
ERROR:  Could not find a valid gem 'forwardable' (>= 0) in any repository
ERROR:  Possible alternatives: forwardablex, formidable, forward-rbase, forwarder2, commandable
```
