### ISSUE TITLE
Unexpected Behavior for Hypen Input

### ISSUE THREAD

**Issue by DanielRuskin1** [RubyMoney/monetize#50]
I've noticed some unexpected behavior with hyphen input in version 1.1.0.

```
[11] pry(main)> "-foo".to_money("USD")
=> #<Money fractional:0 currency:USD>
[12] pry(main)> "--foo".to_money("USD")
ArgumentError: Invalid currency amount (hyphen)
from .rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/monetize-1.1.0/lib/monetize.rb:85:in `extract_cents'
```

I think this is happening because the gem is interpreting the first hyphen as a negative indicator - but the second hyphen as an invalid character (see https://github.com/RubyMoney/monetize/blob/master/lib/monetize.rb#L98).  Considering that other special characters generate a zero amount (e.g. `"$|}{&*#(*".to_money("USD")`), it seems more intuitive to have a hyphen counted as a valid character.

Can the hyphen check on https://github.com/RubyMoney/monetize/blob/master/lib/monetize.rb#L104 be removed, or is it serving another purpose?

**Comment by semmons99** [comment]
Feel free to submit a PR to address this, but it's one reason I always encourage people to create their own parser instead of using monetize.

**Comment by DanielRuskin1** [comment]
Makes sense, thanks @semmons99.

Do you know what purpose the hyphen check (https://github.com/RubyMoney/monetize/blob/master/lib/monetize.rb#L104) is currently serving?  It seems like just rescuing that error on https://github.com/RubyMoney/monetize/blob/master/lib/monetize.rb#L49 and returning zero should help, happy to open a PR with tests if you agree.

**Comment by semmons99** [comment]
I honestly don't remember, it's probably historically from inside the money gem before it was ripped out. Unfortunately we can't really remove it without affecting existing users.

**Comment by DanielRuskin1** [comment]
Hm - do you think we can just rescue and return 0?

**Comment by semmons99** [comment]
People have been expecting an error for years now. Is there a big upside to changing this functionality for everyone?

**Comment by DanielRuskin1** [comment]
I guess the primary goal would be to make the error handling more
consistent.  Pretty much all other malformed input cases result in a 0
money amount.

Maybe remove this in a new release?

**Comment by semmons99** [comment]
I’m okay removing it an bumping the major version, if everything else is made consistent with it.

**Comment by DanielRuskin1** [comment]
Cool.  I'll make that change when I have some extra time.

Thanks for the responsiveness here.

**Comment by ct-clearhaus** [comment]
Would similar behaviour to 'String#to_i' be expected by most people?
```ruby
2.2.1 :001 > '-foo'.to_i
 => 0 
2.2.1 :002 > '--foo'.to_i
 => 0 
```

**Comment by DanielRuskin1** [comment]
That's what I would expect.

I haven't gotten around to opening a pull request for this yet,
unfortunately - hoping to make the change soon.
