### ISSUE TITLE
Stricter parse method

### ISSUE THREAD

**Issue by 23tux** [RubyMoney/monetize#51]
Hi,

would it be possible, to include a method `Monetize("12.34$")` that raises an error, when non parsable values are passed? I like this behaviour from the Ruby core, when you try to use

```
"foobar".to_f # => 0.0
Float("foobar") # => ArgumentError: invalid value for Float(): "foobar"
```

Sometimes I want to raise a validation error in my API, when the user submits nonsense. It's very confusing when nonsense is parsed to `0.0` ;)

This behaviour can be seen at some core types like `Float`, `Integer` or `Array`, so I think it would be a best practise to stick to this convention.

**Comment by semmons99** [comment]
I'd accept a mode that allows this to toggle.
