### ISSUE TITLE
What broke with v1.0.0?

### ISSUE THREAD

**Issue by vemv-kantox** [RubyMoney/monetize#53]
Hi,

our Gemfile.lock entry for monetize is locked at 0.4.1, and it's not apparent to know what broke with the 1.0.0 release. Commit doesn't give the info https://github.com/RubyMoney/monetize/commit/8df488b9f269bfb5f28fbc4090a3b417a13d8054 and there's no entry in the changelog either!

Please clarify.

Thanks much!

Victor

**Comment by semmons99** [comment]
You'll need to compare (or run a diff). Hopefully nothing broke.
