### ISSUE TITLE
Issue 28 being ignored?

### ISSUE THREAD

**Issue by HaleTom** [RubyMoney/monetize#62]
This is a meta issue.

Comments on Issue #28 seem to be getting ignored. 

If this is intentional - cool, can someone just say why?

**Comment by semmons99** [comment]
We have a policy that if no one is working the issue it is closed. If you want to work on it, create a new pull request. 

- shane

**Comment by antstorm** [comment]
@HaleTom ruby 2.3 with `monetize` @ `master`:

```
>> def format_code_value(money, decimal_places = 2)
>>   sprintf "%s %.#{decimal_places}f", money.currency, money.to_f
>> end
=> :format_code_value

>> Money.infinite_precision = true
=> true

>> c = Money::Currency.new :usd
=> #<Money::Currency id: usd, priority: 1, symbol_first: true, thousands_separator: ,, html_entity: $, decimal_mark: ., name: United States Dollar, symbol: $, subunit_to_unit: 100, exponent: 2, iso_code: USD, iso_numeric: 840, subunit: Cent, smallest_denomination: 1>

>> value = 1.234567890123456789
=> 1.2345678901234567

>> m1 = Monetize.parse(value, c)
=> #<Money fractional:0.12345678901234567E3 currency:USD>

>> m2 = Money.new(value * c.subunit_to_unit, c)
=> #<Money fractional:0.123456789012346E3 currency:USD>

>> puts format_code_value(m1, 20)
USD 1.23456789012345669043
=> nil

>> puts format_code_value(m2, 20)
USD 1.23456789012346002110
=> nil
```

It does seem to loose a bit of precision there, but nothing dramatic. The code was copied from your post in #28 directly into the console.

**Comment by antstorm** [comment]
Checked against all the local rubies I had installed — `2.3.0`, `2.2.2`, `2.1.5`, `2.0.0-p648`, `1.9.3-p551`. Same output up to 15 digits after the `.`.

**Comment by HaleTom** [comment]
This sounds like an insidious bug if it's pretending to be infinite precision but actually losing precision.

I worked in a bank, and this makes me cringe.

Sadly, I don't have time to put into looking at this right now.

**Comment by antstorm** [comment]
@HaleTom managed to get to the bottom of this. It's not an issue with `money` or `monetize`. There's a fault in your example:

```ruby
>> value = 1.234567890123456789
=> 1.2345678901234567
```

Because you've used `Float` in your example, you just lost 2 digits of precision from the very beginning. Also it's worth noting `BigDecimal` should be used for precise calculations instead of `Float`. Here's why (`value` comes from the previous code block):

```ruby
>> sprintf "%.20f", value
=> "1.23456789012345669043"
```

**Comment by antstorm** [comment]
#68 fixes an issue with passing `Monetize.parse` a `BigDecimal` input.

Btw, by the looks of it `.parse` wasn't meant for any non-String input, which is also why it wasn't tested for it.

**Comment by HaleTom** [comment]
Thanks @antstorm
