### ISSUE TITLE
Make :assume_from_symbol true by default

### ISSUE THREAD

**Issue by umate** [RubyMoney/monetize#69]
Parsing currency symbols should be enabled by default. I missed that in the beginning, tested on USD and now having issues with wrong data in the DB.

What was the intense to make that `false` by default?

**Comment by antstorm** [comment]
I'm not sure what was the intent, but it was `false` from the very introduction of that feature. I guess it's based on the fact that all the symbols are listed explicitly, duplicating behaviour of `money` gem a bit.

I think it makes sense to get rid of this option and do both ISO code and symbol parsing. And also rely on `money` gem as the source for different possible symbols.

**Comment by umate** [comment]
@antstorm make more sense to rely on money gem and pull all iso currencies code, symbols from there.

**Comment by ct-clearhaus** [comment]
(Ref. https://github.com/RubyMoney/monetize/pull/71#issuecomment-227686374)

I really don't know. Possibly the following is purely hypothetical:

> User inputs the string `"garbage 123"` for any value of `garbage`. Since my application only uses the default currency, I trust Monetize to return me Money for the given amount in "my currency".

In that case, the application should really sanitize the user input, but I guess that's what Monetize is trying to do for you automagically. With `assume_from_symbol` by default, this wouldn't be as expected by the "me" above; it might be "least surprise" though, but I guess it's a breaking change (depending on the contract). Automagic is never gonna work for everyone, but it's all good if it just works for the (vast?) majority. And the majority ... I don't know the majority of use cases.

I avoid using Monetize and also contemplate on doing something much simpler than Money, so I might be a rather bad data point.

**Comment by antstorm** [comment]
@ct-clearhaus yeah, you're right. Although it seems that parsing strings like "symbol/iso_code amount" shouldn't be that hard… I'll take a closer look at how this can be implemented.

**Comment by esergion** [comment]
I think that this is not a good idea, at least for now, coz we first need some kind of workaround for this case (for example):
```
> Monetize.parse('RUB 1000')
=> #<Money fractional:100000 currency:RUB>
> Monetize.assume_from_symbol = true
=> true
> Monetize.parse('RUB 1000')
=> #<Money fractional:100000 currency:ZAR>
```

**Comment by antstorm** [comment]
@esergion oh, wow, didn't know of this one. Will have a look!
