### ISSUE TITLE
Option to swallow exceptions

### ISSUE THREAD

**Issue by smudge** [RubyMoney/monetize#74]
From what I can tell, there are two exceptions that `.parse` (and `#to_money`) might throw when passed a string value:

```ruby
Monetize.parse('100 OMG')
# => Money::Currency::UnknownCurrency: Unknown currency 'omg'
```

```ruby
Monetize.parse('100-500')
# => ArgumentError: Invalid currency amount (hyphen)
```

The problem is that for 99.99% of all other possible inputs, this gem will sanitize/normalize the value and return something, no matter how nonsensical. (A couple of my favorites: `3:00pm` => `$300`, `1/21/1989` => `$1,211,989`.) I honestly see this behavior as a feature, not a bug.

So it's common to just pass user input straight into this gem and let the gem sort it out. (App developers can and **should** still validate the original input value based on how strict they want to be, but that's on them to decide.) For the most part, this gem *just works* (as long as you don't trust it to validate your inputs).

What would be great is if for those 0.01% of times when someone enters something that will cause this gem to blow up, there were an option to swallow exceptions and just return `nil` instead.

The alternative is to catch those two exceptions inside of application/business logic, which isn't the end of the world, but the above cases are *so* uncommon that I suspect most devs won't bother until something hits them in production. The `money-rails` gem already handles these two exceptions, but arguably it wouldn't have to if such an option existed:

https://github.com/RubyMoney/money-rails/blob/9615936407b882c26a976e255130ccba9da9daf2/lib/money-rails/active_record/monetizable.rb#L175

Thoughts?

**Edit:** Happy to produce a PR if there is any agreement on this.

**Comment by antstorm** [comment]
@smudge very good point indeed! Couple of thoughts on this:

1. All the errors thrown while parsing input should subclasses of `Monetize::ParseError`, making it a matter of rescuing this one class when needed.
2. Sometimes you just want `nil` back, absolutely true. I'm thinking `parse` & `parse!` in the spirit of Rails' persistence methods. The only thing I'm a bit worried here is changing the API a bit (original `parse` method becoming a silenced version), but since most of the people use it via `money-rails`, I think it's fine as long as these two work together.

P.S. Love the `3:00pm` and `1/21/1989` examples :)

**Comment by smudge** [comment]
I like the idea of `parse` and `parse!`. The `money-rails` gem has an optional `raise_error_on_money_parsing` config which would need some adjustments, so I'd recommend bumping the 'minor' version number in case anyone was relying on that behavior.

**Comment by antstorm** [comment]
@smudge #75 will allow for better rescuing from errors. This is a pre-cursor to `parse!`.

**Comment by smudge** [comment]
Just created #78 as a follow-up PR. But I think you've basically addressed this issue (aside from maybe a minor version bump, or however you want to handle that). Gonna close this issue now. Thanks!

**Comment by antstorm** [comment]
Yeah, it needs a version bump along with `money-rails` update. Will handle that.
