### ISSUE TITLE
Accounting negative isn't recognized

### ISSUE THREAD

**Issue by inopinatus** [RubyMoney/monetize#82]
surely (but not currently):

`Monetize.parse("$(516.90)") == Money.new(-51690, "USD") # => true`

**Comment by ct-clearhaus** [comment]
Using money 6.1.1 and monetize 0.3.0 I get
```
irb(main):003:0> Monetize.parse("$(516.90)") == Money.new(-51690, 'USD')
=> false
```

**Comment by inopinatus** [comment]
yes I mean it should be true, but it isn't. seems monetize doesn't recognize the bookkeeping-style negative.

**Comment by antstorm** [comment]
@inopinatus sounds like a good PR opportunity ;)

**Comment by macosgrove** [comment]
I came across this same issue when attempting to use Monetize to convert the subtotal of a credit line from a Recurly invoice into cents.

```pry(main)> Monetize.parse("($228.00)").cents == -22800
=> false```
 
I expected ```Monetize.parse("($228.00)").cents == -22800``` to be true

**Comment by antstorm** [comment]
It might make sense to implement this, but hide behind an option, because it might be quite misleading to people who aren't accountants

**Comment by inopinatus** [comment]
@semmons99 was this closed because you don't agree that Monetize should correctly parse the accounting negative, or for some other reason?

**Comment by semmons99** [comment]
Since it was never opened as a PR and has not been commented on in 2 years, I closed it. Happy to accept a PR that understands this with an appropriate option to enable it.
