### ISSUE TITLE
Ruby 2.4.0 FixNum is deprecated warning

### ISSUE THREAD

**Issue by chrisjeon** [RubyMoney/monetize#84]
I'm using the money-rails gem https://github.com/RubyMoney/money-rails

and after upgrading to ruby 2.4.0, I'm getting this deprecation warning when running tests.

`/Users/chrisjeon/.rvm/gems/ruby-2.4.0/gems/monetize-1.4.0/lib/monetize.rb:87: warning: constant ::Fixnum is deprecated             ] 47% Time: 00:00:30,  ETA: 00:00:34`

Screenshot attached.

![screen shot 2016-12-25 at 12 52 26 pm](https://cloud.githubusercontent.com/assets/2433941/21472304/236e5c54-caa1-11e6-93d4-7aec51c1a216.png)

**Comment by antstorm** [comment]
@chrisjeon good spot, thanks! Started work on ruby 2.4.0 support — #85

**Comment by antstorm** [comment]
#87
