### ISSUE TITLE
Add gem money as dependency

### ISSUE THREAD

**Issue by januszm** [RubyMoney/monetize#93]
Looks like this gem requires gem money to work

```
gems/monetize-0.1.4/lib/monetize.rb:3:in `require': cannot load such file -- money (LoadError)
```

Why don't we add 'money' to runtime dependencies?

**Comment by antstorm** [comment]
@januszm but it is listed as gem's dependency (from `monetize.gemspec`):

```ruby
spec.add_dependency 'money', '~> 6.8'
```

How did you install it?

**Comment by januszm** [comment]
That's weir. I added it as `gem 'monetize'` entry in `Gemfile` in Rails application

**Comment by antstorm** [comment]
Can you please remove it from the Gemfile, re-bundle the gems and paste here `monetize` dependencies from your `Gemfile.lock`?
