### ISSUE TITLE
Add LKR as the currency & got the wrong unicode as the symbol

### ISSUE THREAD

**Issue by dilumn** [RubyMoney/monetize#96]
Hi, I'm from Sri Lanka & our currency is LKR. So I pass LKR like this,

`Monetize.parse([amount, "LKR" ].join)`

But I'm getting is `444.00&nbsp;&#x0BF9;` which is `444.00 ௹`. LKR should display like `Rs 444.00`

How can I fix this issue??

**Comment by antstorm** [comment]
I don't think this issue is related to `monetize`, Here's the output that I'm getting:

<img width="335" alt="screenshot 2017-04-04 14 38 36" src="https://cloud.githubusercontent.com/assets/118353/24659399/7d3b881e-1944-11e7-9c05-89b9399ed591.png">

**Comment by dilumn** [comment]
Created a pull request to fix the `html_entity` symbol issue.
